### PR TITLE
add lightning solver

### PR DESCRIPTION
**Pull request by mathurinm**
ping  @klopfe

### CODE REVIEW

**Comment by agramfort** [comment]
Can you share a plot ?

**Comment by mathurinm** [comment]
image


This is with the current simulated dataset. The setup `n << p` is not the most relevant for SVM, but that's for another PR.

**Review by tomMoral — APPROVED** [review]
LGTM!

The plot seems to show good convergence.

**Comment by agramfort** [comment]
thx @mathurinm !

**Pull request merged**
